name: LLMS Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  llms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout client repo (Telucero/workflows)
        uses: actions/checkout@v3

      - name: Checkout kluster-mkdocs repo
        uses: actions/checkout@v3
        with:
          repository: Telucero/kluster-mkdocs
          path: kluster-mkdocs

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install pyyaml requests beautifulsoup4

      - name: Run LLMS Generator
        uses: Telucero/workflows/llms_scripts@Central_repo_test
        with:
          docs_path: llms-output
          config_path: kluster-mkdocs/kluster-docs/variables.yml

      - name: Upload LLMS Output as Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: llms-output
          path: |
            llms-output/llms-full.txt
            llms-output/llms.txt
            llms-output/llms-files/
