name: Call Deploy Docs

on:
  push:
    branches:
      - main  # Or adjust as needed for your workflow

jobs:
  call-deploy:
    uses: Telucero/workflows/.github/workflows/deploy-docs.yml@Central_repo_test  
    with:
      branch: main  # Branch to deploy from in the docs repo
      repository: Telucero/wormhole-docs  # Repo with the MkDocs content
      path: wormhole-docs  # Directory name to clone into
      url_prefix: wormhole-mkdocs  # Used to rewrite links
      submodules: true  # Optional, set to false if not using submodules
    secrets: inherit  # Allow access to GitHub token and other secrets
